import { defineTheme } from '../../factory.js'

export const amberTheme = defineTheme({
  name: 'amber',
  label: 'Warm Amber',
  light: {
    background:          'amber-50',
    foreground:          'amber-950',
    card:                'white',
    cardForeground:      'amber-950',
    popover:             'white',
    popoverForeground:   'amber-950',
    primary:             'amber-600',
    primaryForeground:   'white',
    secondary:           'yellow-100',
    secondaryForeground: 'yellow-900',
    muted:               'amber-100',
    mutedForeground:     'amber-600',
    accent:              'yellow-100',
    accentForeground:    'yellow-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'amber-200',
    input:               'amber-200',
    ring:                'amber-600',
  },
  dark: {
    background:          'stone-950',
    foreground:          'amber-50',
    card:                'stone-900',
    cardForeground:      'amber-50',
    popover:             'stone-950',
    popoverForeground:   'amber-50',
    primary:             'amber-400',
    primaryForeground:   'stone-950',
    secondary:           'stone-800',
    secondaryForeground: 'amber-200',
    muted:               'stone-800',
    mutedForeground:     'stone-400',
    accent:              'stone-800',
    accentForeground:    'amber-200',
    destructive:         'red-400',
    destructiveForeground: 'stone-950',
    border:              'stone-800',
    input:               'stone-800',
    ring:                'amber-400',
  },
  radius: '0.5rem',
})
