import { defineTheme } from '../../factory.js'

export const candyTheme = defineTheme({
  name: 'candy',
  label: 'Candy',
  light: {
    background:          'pink-50',
    foreground:          'pink-950',
    card:                'white',
    cardForeground:      'pink-950',
    popover:             'white',
    popoverForeground:   'pink-950',
    primary:             'fuchsia-600',
    primaryForeground:   'white',
    secondary:           'pink-100',
    secondaryForeground: 'pink-900',
    muted:               'pink-100',
    mutedForeground:     'pink-500',
    accent:              'purple-100',
    accentForeground:    'purple-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'pink-200',
    input:               'pink-200',
    ring:                'fuchsia-600',
  },
  dark: {
    background:          'neutral-950',
    foreground:          'pink-50',
    card:                'neutral-900',
    cardForeground:      'pink-50',
    popover:             'neutral-950',
    popoverForeground:   'pink-50',
    primary:             'fuchsia-400',
    primaryForeground:   'neutral-950',
    secondary:           'neutral-800',
    secondaryForeground: 'pink-200',
    muted:               'neutral-800',
    mutedForeground:     'neutral-400',
    accent:              'purple-900',
    accentForeground:    'purple-100',
    destructive:         'red-400',
    destructiveForeground: 'neutral-950',
    border:              'neutral-800',
    input:               'neutral-800',
    ring:                'fuchsia-400',
  },
  radius: '1rem',
})
