import { defineTheme } from '../../factory.js'

export const defaultTheme = defineTheme({
  name: 'default',
  label: 'Default',
  light: {
    background:          'zinc-50',
    foreground:          'zinc-950',
    card:                'white',
    cardForeground:      'zinc-950',
    popover:             'white',
    popoverForeground:   'zinc-950',
    primary:             'zinc-900',
    primaryForeground:   'zinc-50',
    secondary:           'zinc-100',
    secondaryForeground: 'zinc-900',
    muted:               'zinc-100',
    mutedForeground:     'zinc-500',
    accent:              'zinc-100',
    accentForeground:    'zinc-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'zinc-200',
    input:               'zinc-200',
    ring:                'zinc-950',
  },
  dark: {
    background:          'zinc-950',
    foreground:          'zinc-50',
    card:                'zinc-900',
    cardForeground:      'zinc-50',
    popover:             'zinc-950',
    popoverForeground:   'zinc-50',
    primary:             'zinc-50',
    primaryForeground:   'zinc-900',
    secondary:           'zinc-800',
    secondaryForeground: 'zinc-50',
    muted:               'zinc-800',
    mutedForeground:     'zinc-400',
    accent:              'zinc-800',
    accentForeground:    'zinc-50',
    destructive:         'red-400',
    destructiveForeground: 'zinc-950',
    border:              'zinc-800',
    input:               'zinc-800',
    ring:                'zinc-300',
  },
  radius: '0.5rem',
})
