import { defineTheme } from '../../factory.js'

export const forestTheme = defineTheme({
  name: 'forest',
  label: 'Forest Green',
  light: {
    background:          'stone-50',
    foreground:          'stone-950',
    card:                'white',
    cardForeground:      'stone-950',
    popover:             'white',
    popoverForeground:   'stone-950',
    primary:             'green-700',
    primaryForeground:   'white',
    secondary:           'emerald-100',
    secondaryForeground: 'emerald-900',
    muted:               'stone-100',
    mutedForeground:     'stone-500',
    accent:              'emerald-100',
    accentForeground:    'emerald-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'stone-200',
    input:               'stone-200',
    ring:                'green-700',
  },
  dark: {
    background:          'stone-950',
    foreground:          'stone-50',
    card:                'stone-900',
    cardForeground:      'stone-50',
    popover:             'stone-950',
    popoverForeground:   'stone-50',
    primary:             'green-400',
    primaryForeground:   'stone-950',
    secondary:           'stone-800',
    secondaryForeground: 'stone-200',
    muted:               'stone-800',
    mutedForeground:     'stone-400',
    accent:              'stone-800',
    accentForeground:    'stone-200',
    destructive:         'red-400',
    destructiveForeground: 'stone-950',
    border:              'stone-800',
    input:               'stone-800',
    ring:                'green-400',
  },
  radius: '0.375rem',
})
