import { defineTheme } from '../../factory.js'

export const indigoTheme = defineTheme({
  name: 'indigo',
  label: 'Deep Indigo',
  light: {
    background:          'slate-50',
    foreground:          'slate-950',
    card:                'white',
    cardForeground:      'slate-950',
    popover:             'white',
    popoverForeground:   'slate-950',
    primary:             'indigo-600',
    primaryForeground:   'white',
    secondary:           'indigo-100',
    secondaryForeground: 'indigo-900',
    muted:               'slate-100',
    mutedForeground:     'slate-500',
    accent:              'violet-100',
    accentForeground:    'violet-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'slate-200',
    input:               'slate-200',
    ring:                'indigo-600',
  },
  dark: {
    background:          'slate-950',
    foreground:          'slate-50',
    card:                'slate-900',
    cardForeground:      'slate-50',
    popover:             'slate-950',
    popoverForeground:   'slate-50',
    primary:             'indigo-400',
    primaryForeground:   'slate-950',
    secondary:           'slate-800',
    secondaryForeground: 'slate-200',
    muted:               'slate-800',
    mutedForeground:     'slate-400',
    accent:              'violet-900',
    accentForeground:    'violet-100',
    destructive:         'red-400',
    destructiveForeground: 'slate-950',
    border:              'slate-800',
    input:               'slate-800',
    ring:                'indigo-400',
  },
  radius: '0.5rem',
})
