import { defineTheme } from '../../factory.js'

export const midnightTheme = defineTheme({
  name: 'midnight',
  label: 'Midnight',
  light: {
    background:          'slate-100',
    foreground:          'slate-950',
    card:                'white',
    cardForeground:      'slate-950',
    popover:             'white',
    popoverForeground:   'slate-950',
    primary:             'indigo-700',
    primaryForeground:   'white',
    secondary:           'slate-200',
    secondaryForeground: 'slate-800',
    muted:               'slate-100',
    mutedForeground:     'slate-500',
    accent:              'indigo-100',
    accentForeground:    'indigo-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'slate-200',
    input:               'slate-200',
    ring:                'indigo-700',
  },
  dark: {
    background:          'slate-950',
    foreground:          'slate-100',
    card:                'slate-900',
    cardForeground:      'slate-100',
    popover:             'slate-950',
    popoverForeground:   'slate-100',
    primary:             'indigo-400',
    primaryForeground:   'slate-950',
    secondary:           'slate-800',
    secondaryForeground: 'slate-200',
    muted:               'slate-800',
    mutedForeground:     'slate-400',
    accent:              'indigo-900',
    accentForeground:    'indigo-100',
    destructive:         'red-400',
    destructiveForeground: 'slate-950',
    border:              'slate-800',
    input:               'slate-800',
    ring:                'indigo-400',
  },
  radius: '0.25rem',
})
