import { defineTheme } from '../../factory.js'

export const roseTheme = defineTheme({
  name: 'rose',
  label: 'Rose Pink',
  light: {
    background:          'rose-50',
    foreground:          'rose-950',
    card:                'white',
    cardForeground:      'rose-950',
    popover:             'white',
    popoverForeground:   'rose-950',
    primary:             'rose-600',
    primaryForeground:   'white',
    secondary:           'pink-100',
    secondaryForeground: 'pink-900',
    muted:               'rose-100',
    mutedForeground:     'rose-500',
    accent:              'pink-100',
    accentForeground:    'pink-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'rose-200',
    input:               'rose-200',
    ring:                'rose-600',
  },
  dark: {
    background:          'neutral-950',
    foreground:          'rose-50',
    card:                'neutral-900',
    cardForeground:      'rose-50',
    popover:             'neutral-950',
    popoverForeground:   'rose-50',
    primary:             'rose-400',
    primaryForeground:   'neutral-950',
    secondary:           'neutral-800',
    secondaryForeground: 'rose-200',
    muted:               'neutral-800',
    mutedForeground:     'neutral-400',
    accent:              'neutral-800',
    accentForeground:    'rose-200',
    destructive:         'red-400',
    destructiveForeground: 'neutral-950',
    border:              'neutral-800',
    input:               'neutral-800',
    ring:                'rose-400',
  },
  radius: '0.75rem',
})
