import { defineTheme } from '../../factory.js'

export const sunsetTheme = defineTheme({
  name: 'sunset',
  label: 'Sunset Orange',
  light: {
    background:          'orange-50',
    foreground:          'orange-950',
    card:                'white',
    cardForeground:      'orange-950',
    popover:             'white',
    popoverForeground:   'orange-950',
    primary:             'orange-600',
    primaryForeground:   'white',
    secondary:           'amber-100',
    secondaryForeground: 'amber-900',
    muted:               'orange-100',
    mutedForeground:     'orange-500',
    accent:              'amber-100',
    accentForeground:    'amber-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'orange-200',
    input:               'orange-200',
    ring:                'orange-600',
  },
  dark: {
    background:          'stone-950',
    foreground:          'orange-50',
    card:                'stone-900',
    cardForeground:      'orange-50',
    popover:             'stone-950',
    popoverForeground:   'orange-50',
    primary:             'orange-400',
    primaryForeground:   'stone-950',
    secondary:           'stone-800',
    secondaryForeground: 'orange-200',
    muted:               'stone-800',
    mutedForeground:     'stone-400',
    accent:              'stone-800',
    accentForeground:    'orange-200',
    destructive:         'red-400',
    destructiveForeground: 'stone-950',
    border:              'stone-800',
    input:               'stone-800',
    ring:                'orange-400',
  },
  radius: '0.5rem',
})
