import { defineTheme } from '../../factory.js'

export const tealTheme = defineTheme({
  name: 'teal',
  label: 'Teal',
  light: {
    background:          'teal-50',
    foreground:          'teal-950',
    card:                'white',
    cardForeground:      'teal-950',
    popover:             'white',
    popoverForeground:   'teal-950',
    primary:             'teal-600',
    primaryForeground:   'white',
    secondary:           'cyan-100',
    secondaryForeground: 'cyan-900',
    muted:               'teal-100',
    mutedForeground:     'teal-600',
    accent:              'cyan-100',
    accentForeground:    'cyan-900',
    destructive:         'red-600',
    destructiveForeground: 'white',
    border:              'teal-200',
    input:               'teal-200',
    ring:                'teal-600',
  },
  dark: {
    background:          'slate-950',
    foreground:          'teal-50',
    card:                'slate-900',
    cardForeground:      'teal-50',
    popover:             'slate-950',
    popoverForeground:   'teal-50',
    primary:             'teal-400',
    primaryForeground:   'slate-950',
    secondary:           'slate-800',
    secondaryForeground: 'teal-200',
    muted:               'slate-800',
    mutedForeground:     'slate-400',
    accent:              'slate-800',
    accentForeground:    'teal-200',
    destructive:         'red-400',
    destructiveForeground: 'slate-950',
    border:              'slate-800',
    input:               'slate-800',
    ring:                'teal-400',
  },
  radius: '0.5rem',
})
