export type ThemePickerLabels = Record<string, Record<string, string>> | undefined

export const DEFAULT_LABELS: Record<'en' | 'es' | 'pt', Record<string, string>> = {
  en: {
    'ui.primary': 'Primary',
    'ui.secondary': 'Secondary',
    'ui.accent': 'Accent',
    'ui.neutralBase': 'Neutral base',
    'ui.auto': 'Auto',
    'ui.usingPreset': 'Using preset',
    'ui.autoFromPrimary': 'Auto from primary',
    'ui.autoFromSecondary': 'Auto from secondary',
    'ui.primaryFamily': 'Primary family',
    'ui.surfacesSuffix': 'surfaces',
    'ui.pattern': 'Pattern',
    'ui.pattern.none': 'No pattern',
    'ui.pattern.tint': 'Tint',
    'ui.pattern.tint.foreground': 'Foreground',
    'ui.pattern.tint.primary': 'Primary',
    'ui.pattern.tint.secondary': 'Secondary',
    'ui.pattern.tint.accent': 'Accent',
    'ui.pattern.size': 'Size',
    'ui.pattern.density': 'Density',
    'ui.backgroundImage': 'Background Image',
    'ui.backgroundPlaceholder': "https://… or url('…') or gradient CSS",
    'ui.clear': 'Clear',
    'ui.patternOverlayHint': 'Pattern always overlays on top of background image.',
    'ui.overrideOnPreset': 'overrides on preset',
    'ui.font.body': 'body',
    'ui.font.heading': 'heading',
    'ui.font.sameAsBody': 'Same as body',
    'ui.font.systemDefault': 'System default',
    'ui.font.systemDefaultSans': 'System default (sans-serif)',
    'ui.font.systemSerif': 'System serif',
    'ui.size.sm': 'SM',
    'ui.size.md': 'MD',
    'ui.size.lg': 'LG',
    'ui.opacity.subtle': 'Subtle',
    'ui.opacity.normal': 'Normal',
    'ui.opacity.bold': 'Bold',
    'ui.neutral.none': 'None',
    'ui.filter.all': 'All',
    'ui.filter.curated': 'Featured',
    'ui.filter.basic': 'Basic',
    'ui.filter.claude': 'Studio',
    'ui.filter.tweakcn': 'Signature',
    'ui.filter.community': 'Community',
  },
  es: {
    'ui.primary': 'Primario',
    'ui.secondary': 'Secundario',
    'ui.accent': 'Acento',
    'ui.neutralBase': 'Base neutral',
    'ui.auto': 'Auto',
    'ui.usingPreset': 'Usando preset',
    'ui.autoFromPrimary': 'Auto desde primario',
    'ui.autoFromSecondary': 'Auto desde secundario',
    'ui.primaryFamily': 'Familia primaria',
    'ui.surfacesSuffix': 'superficies',
    'ui.pattern': 'Patrón',
    'ui.pattern.none': 'Sin patrón',
    'ui.pattern.tint': 'Tinte',
    'ui.pattern.tint.foreground': 'Primer plano',
    'ui.pattern.tint.primary': 'Primario',
    'ui.pattern.tint.secondary': 'Secundario',
    'ui.pattern.tint.accent': 'Acento',
    'ui.pattern.size': 'Tamaño',
    'ui.pattern.density': 'Densidad',
    'ui.backgroundImage': 'Imagen de fondo',
    'ui.backgroundPlaceholder': "https://… o url('…') o CSS de gradiente",
    'ui.clear': 'Borrar',
    'ui.patternOverlayHint': 'El patrón siempre se superpone a la imagen de fondo.',
    'ui.overrideOnPreset': 'sobrescribe el preset',
    'ui.font.body': 'cuerpo',
    'ui.font.heading': 'títulos',
    'ui.font.sameAsBody': 'Igual que cuerpo',
    'ui.font.systemDefault': 'Por defecto del sistema',
    'ui.font.systemDefaultSans': 'Por defecto del sistema (sans-serif)',
    'ui.font.systemSerif': 'Serif del sistema',
    'ui.size.sm': 'SM',
    'ui.size.md': 'MD',
    'ui.size.lg': 'LG',
    'ui.opacity.subtle': 'Sutil',
    'ui.opacity.normal': 'Normal',
    'ui.opacity.bold': 'Fuerte',
    'ui.neutral.none': 'Ninguno',
    'ui.filter.all': 'Todos',
    'ui.filter.curated': 'Destacados',
    'ui.filter.basic': 'Básicos',
    'ui.filter.claude': 'Studio',
    'ui.filter.tweakcn': 'Signature',
    'ui.filter.community': 'Comunidad',
  },
  pt: {
    'ui.primary': 'Primário',
    'ui.secondary': 'Secundário',
    'ui.accent': 'Destaque',
    'ui.neutralBase': 'Base neutra',
    'ui.auto': 'Auto',
    'ui.usingPreset': 'Usando preset',
    'ui.autoFromPrimary': 'Auto do primário',
    'ui.autoFromSecondary': 'Auto do secundário',
    'ui.primaryFamily': 'Família primária',
    'ui.surfacesSuffix': 'superfícies',
    'ui.pattern': 'Padrão',
    'ui.pattern.none': 'Sem padrão',
    'ui.pattern.tint': 'Tonalidade',
    'ui.pattern.tint.foreground': 'Primeiro plano',
    'ui.pattern.tint.primary': 'Primário',
    'ui.pattern.tint.secondary': 'Secundário',
    'ui.pattern.tint.accent': 'Destaque',
    'ui.pattern.size': 'Tamanho',
    'ui.pattern.density': 'Densidade',
    'ui.backgroundImage': 'Imagem de fundo',
    'ui.backgroundPlaceholder': "https://… ou url('…') ou CSS de gradiente",
    'ui.clear': 'Limpar',
    'ui.patternOverlayHint': 'O padrão sempre sobrepõe a imagem de fundo.',
    'ui.overrideOnPreset': 'sobrescreve o preset',
    'ui.font.body': 'corpo',
    'ui.font.heading': 'títulos',
    'ui.font.sameAsBody': 'Igual ao corpo',
    'ui.font.systemDefault': 'Sistema padrão',
    'ui.font.systemDefaultSans': 'Sistema padrão (sans-serif)',
    'ui.font.systemSerif': 'Sistema serif',
    'ui.size.sm': 'SM',
    'ui.size.md': 'MD',
    'ui.size.lg': 'LG',
    'ui.opacity.subtle': 'Suave',
    'ui.opacity.normal': 'Normal',
    'ui.opacity.bold': 'Forte',
    'ui.neutral.none': 'Nenhum',
    'ui.filter.all': 'Todos',
    'ui.filter.curated': 'Destaques',
    'ui.filter.basic': 'Básicos',
    'ui.filter.claude': 'Studio',
    'ui.filter.tweakcn': 'Signature',
    'ui.filter.community': 'Comunidade',
  },
}

export function translate(labels: ThemePickerLabels, locale: string | undefined, key: string, fallback: string): string {
  const lang = (locale === 'es' || locale === 'pt' || locale === 'en') ? locale : 'en'
  return labels?.[lang]?.[key] ?? DEFAULT_LABELS[lang][key] ?? fallback
}
